[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma db push --skip-generate --accept-data-loss && next start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
